theme: minima
title: Hi! I'm Maryam, Data Engineer and Software Developer!
description: With a strong foundation in software engineering, I have expanded my expertise to include data engineering, AI technologies, and cloud platforms. Currently, I specialize in building scalable data platforms, optimizing database performance, and creating efficient solutions for complex data systems, with a focus on healthcare data warehousing. I also have experience in blockchain and Web3 technologies, including developing smart contracts and decentralized applications.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
